apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-bovj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-aicg-tenant/rhtap-demo-app/hacbs-test-project-bovj@sha256:b386993d2616a7d516cca7758d47ab3b2f0b2c583726fd6ff1ce79ce8cb993a4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
