apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bovj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bovj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-bovj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bovj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bovj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-aicg-tenant/rhtap-demo-app/hacbs-test-project-bovj@sha256:b386993d2616a7d516cca7758d47ab3b2f0b2c583726fd6ff1ce79ce8cb993a4
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
